name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: tox -e py${{ matrix.python-version }}

  lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install tox
        run: pip install tox

      - name: Run ruff
        run: tox -e ruff

